name: Build and Package

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry to use'
        required: true
        default: docker.wso2.com

jobs:
  build:
    runs-on: Runner_integration-web-editor
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ github.event.inputs.registry }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Node.js heap size to 32GB
        run: echo "NODE_OPTIONS=--max-old-space-size=32768" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: wso2/integration-web-editor:latest,wso2/integration-web-editor:1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/devant-editor.tar
          push: true

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ runner.temp }}/devant-editor.tar
